const ERR_OK = 0

// API错误
const ERR_API_BAD_REQ = -1000
const ERR_API_INTERNAL_ERROR = -1001

const ERR_API_NAME_TOO_LONG = -1100
const ERR_API_NAME_TOO_SHORT = -1101
const ERR_API_NICK_TOO_LONG = -1102
const ERR_API_NICK_TOO_SHORT = -1103
const ERR_API_PASSWORD_TOO_LONG = -1104
const ERR_API_PASSWORD_TOO_SHORT = -1105
const ERR_API_NAME_INVALID = -1106
const ERR_API_NICK_INVALID = -1107
const ERR_API_BAD_PASSWORD = -1108
const ERR_API_BAD_TOKEN = -1109
const ERR_API_INVALID_CALL = -1110
const ERR_API_NICK_IN_USE = -1111
const ERR_API_EMAIL_INVALID = -1112

const ERR_API_DB_ERROR = -1200
const ERR_API_CANNOT_REENTER = -1201
const ERR_API_ROOM_NOT_FOUND = -1202
const ERR_API_ROOM_IS_IN_GAME = -1203
const ERR_API_ROOM_IS_FULL = -1204
const ERR_API_ROOM_INVALID_TITLE = -1205
const ERR_API_ROOM_INVALID_PARAM = -1206
const ERR_API_ROOM_NOT_READY = -1207
const ERR_API_GAME_CANNOT_PLAY_CARD = -1208
const ERR_API_GAME_CANNOT_DEAL_CARD = -1209
const ERR_API_GAME_CANNOT_REPORT_NO_UNO = -1210
const ERR_API_ROOM_NOT_OWNER = -1211
const ERR_API_ROOM_UPDATE_SEAT_COOLDOWN = -1212
const ERR_API_ROOM_USE_VOICE_COOLDOWN = -1213
const ERR_API_ROOM_PLAYER_NOT_FOUND = -1214
const ERR_API_ROOM_CANNOT_LEAVE_AT_THIS_TIME = -1215

// DB错误
const ERR_DB_EXISTS = -2000
const ERR_DB_NOT_EXISTS = -2001

// 导出
export default {
  ERR_OK,

  ERR_API_BAD_REQ,
  ERR_API_INTERNAL_ERROR,

  ERR_API_NAME_TOO_LONG,
  ERR_API_NAME_TOO_SHORT,
  ERR_API_NICK_TOO_LONG,
  ERR_API_NICK_TOO_SHORT,
  ERR_API_PASSWORD_TOO_LONG,
  ERR_API_PASSWORD_TOO_SHORT,
  ERR_API_NAME_INVALID,
  ERR_API_NICK_INVALID,
  ERR_API_BAD_PASSWORD,
  ERR_API_BAD_TOKEN,
  ERR_API_INVALID_CALL,
  ERR_API_NICK_IN_USE,
  ERR_API_EMAIL_INVALID,

  ERR_API_DB_ERROR,
  ERR_API_CANNOT_REENTER,
  ERR_API_ROOM_NOT_FOUND,
  ERR_API_ROOM_IS_IN_GAME,
  ERR_API_ROOM_IS_FULL,
  ERR_API_ROOM_INVALID_TITLE,
  ERR_API_ROOM_INVALID_PARAM,
  ERR_API_ROOM_NOT_READY,
  ERR_API_GAME_CANNOT_PLAY_CARD,
  ERR_API_GAME_CANNOT_DEAL_CARD,
  ERR_API_GAME_CANNOT_REPORT_NO_UNO,
  ERR_API_ROOM_NOT_OWNER,
  ERR_API_ROOM_UPDATE_SEAT_COOLDOWN,
  ERR_API_ROOM_USE_VOICE_COOLDOWN,
  ERR_API_ROOM_PLAYER_NOT_FOUND,
  ERR_API_ROOM_CANNOT_LEAVE_AT_THIS_TIME,

  ERR_DB_EXISTS,
  ERR_DB_NOT_EXISTS
}
